# Generated by Django 3.1.2 on 2020-11-02 04:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20201102_0425'),
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(default=1000000000, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('canceled', 'Canceled'), ('pending', 'Pending'), ('complete', 'Complete')], max_length=12)),
                ('response_code', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('transaction_type', models.CharField(max_length=30)),
                ('atm_card_number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.atmcard', verbose_name='atm card number')),
                ('atm_machine_uid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.atmachine', verbose_name='atm machine uid')),
            ],
        ),
    ]
