# Generated by Django 3.1.2 on 2020-11-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('cash-withdrawal', 'Cash Withdrawal'), ('cash-transfer', 'Cash Transfer'), ('balance-inquiry', 'Balance Inquiry')], default='unknown', max_length=30),
        ),
    ]
