# Generated by Django 3.1.2 on 2020-11-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201104_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='response_code',
            field=models.CharField(max_length=3),
        ),
    ]
