# Generated by Django 3.1.2 on 2020-11-02 04:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATMachine',
            fields=[
                ('atm_machine_uid', models.BigIntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('current_balance', models.BigIntegerField()),
                ('location', models.CharField(max_length=100)),
                ('minimum_balance', models.BigIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated')], max_length=15)),
                ('last_refill_date', models.DateField()),
                ('next_maint_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ATMachineRefill',
            fields=[
                ('refill_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('amount', models.BigIntegerField()),
                ('atm_branch', models.CharField(max_length=30)),
                ('refill_date', models.DateField()),
                ('previous_balance', models.BigIntegerField()),
                ('atm_machine_uid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.atmachine', verbose_name='ATM Machine UID')),
            ],
        ),
    ]
