# Generated by Django 3.1.2 on 2020-11-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20201102_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmachine',
            name='last_refill_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='atmachine',
            name='next_maint_date',
            field=models.DateField(null=True),
        ),
    ]
