# Generated by Django 3.1.2 on 2020-11-01 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountExtension',
            fields=[
                ('account_number', models.BigIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('name', models.CharField(max_length=35)),
                ('phone_number', models.CharField(max_length=10)),
                ('balance', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ATMCard',
            fields=[
                ('card_number', models.BigIntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1000000000000000), django.core.validators.MaxValueValidator(9999999999999999)])),
                ('pin', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)])),
                ('name', models.CharField(max_length=35)),
                ('address', models.CharField(max_length=70)),
                ('phone_number', models.CharField(max_length=10)),
                ('card_status', models.CharField(choices=[('active', 'Active'), ('deactivated', 'deactivated')], max_length=15)),
            ],
        ),
    ]
