# Generated by Django 3.1.2 on 2020-11-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201102_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmcard',
            name='two_fact_auth_status',
            field=models.CharField(choices=[('on', 'On'), ('off', 'Off')], default='deactivated', max_length=5),
        ),
        migrations.AlterField(
            model_name='atmcard',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='atmcard',
            name='card_status',
            field=models.CharField(choices=[('active', 'Active'), ('deactivated', 'deactivated')], default='off', max_length=15),
        ),
    ]
