# Generated by Django 3.1.2 on 2020-11-02 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201102_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmcard',
            name='date_issued',
            field=models.DateField(default=datetime.date(2020, 11, 2)),
        ),
        migrations.AddField(
            model_name='atmcard',
            name='expire_date',
            field=models.DateField(default=datetime.date(2020, 11, 2)),
        ),
    ]
