# Generated by Django 3.1.2 on 2020-11-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201102_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountextension',
            name='account_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='atmcard',
            name='card_number',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='atmcard',
            name='pin',
            field=models.CharField(max_length=4),
        ),
    ]
