# Generated by Django 3.1.2 on 2020-11-03 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20201103_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmcard',
            name='account_number',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='user.accountextension', verbose_name='account extension'),
        ),
        migrations.AlterField(
            model_name='atmcard',
            name='card_status',
            field=models.CharField(choices=[('active', 'Active'), ('deactivated', 'deactivated')], default='active', max_length=15),
        ),
        migrations.AlterField(
            model_name='atmcard',
            name='two_fact_auth_status',
            field=models.CharField(choices=[('on', 'On'), ('off', 'Off')], default='off', max_length=5),
        ),
    ]
