# Generated by Django 3.1.3 on 2020-11-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20201103_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountextension',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='atmcard',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
