# Generated by Django 3.1.2 on 2020-11-19 21:10

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20201113_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmcard',
            name='expire_date',
            field=models.DateField(default=user.models.ATMCard.newExpDate),
        ),
    ]
