# Generated by Django 3.1.2 on 2020-11-23 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20201119_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmcard',
            name='card_status',
            field=models.CharField(choices=[('active', 'Active'), ('deactivated', 'deactivated')], default='deactivated', max_length=15),
        ),
    ]
